Debian: split DKMS into separate binary package
The package deps seems to be correct,
and the mod does seem to get built
and placed into initramfs.

```
$ eatmydata sudo dpkg -i bcachefs-tools_1.31.3_amd64.deb
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
(Reading database ... 534575 files and directories currently installed.)
Preparing to unpack bcachefs-tools_1.31.3_amd64.deb ...
Unpacking bcachefs-tools (1:1.31.3) over (1:1.31.3) ...
Setting up bcachefs-tools (1:1.31.3) ...
Processing triggers for man-db (2.13.1-1) ...
$ eatmydata sudo dpkg -i bcachefs-kernel-dkms_1.31.3_amd64.deb
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
(Reading database ... 552274 files and directories currently installed.)
Preparing to unpack bcachefs-kernel-dkms_1.31.3_amd64.deb ...
Unpacking bcachefs-kernel-dkms (1:1.31.3) ...
Setting up bcachefs-kernel-dkms (1:1.31.3) ...
Loading new bcachefs/1.31.1 DKMS files...
Building for 6.16.7+deb14-amd64

Building initial module bcachefs/1.31.1 for 6.16.7+deb14-amd64
Sign command: /lib/modules/6.16.7+deb14-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...

Building module(s)...... done.
Signing module /var/lib/dkms/bcachefs/1.31.1/build/src/fs/bcachefs/bcachefs.ko
Found pre-existing /lib/modules/6.16.7+deb14-amd64/kernel/fs/bcachefs/bcachefs.ko.xz, archiving for uninstallation
Installing /lib/modules/6.16.7+deb14-amd64/updates/dkms/bcachefs.ko.xz
Running depmod.... done.
Processing triggers for initramfs-tools (0.150) ...
update-initramfs: Generating /boot/initrd.img-6.16.7+deb14-amd64
update-initramfs: Generating /boot/initrd.img-6.12.38+deb13-amd64
$ lsinitramfs -l /boot/initrd.img-6.16.7+deb14-amd64 | grep bcachefs
-rw-r--r--   1 root     root      1027492 Sep 18 04:15 usr/lib/modules/6.16.7+deb14-amd64/updates/dkms/bcachefs.ko.xz
-rwxr-xr-x   1 root     root         2042 Sep 18 03:01 scripts/local-premount/bcachefs
-rwxr-xr-x   1 root     root      3791344 Sep 18 03:01 usr/sbin/bcachefs
lrwxrwxrwx   1 root     root            8 Sep 18 04:15 usr/sbin/mount.bcachefs -> bcachefs

```

Signed-off-by: Roman Lebedev <lebedev.ri@gmail.com>